[package]
name = "yamasec20210213"
version = "0.1.0"
authors = ["motchang <motchang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
